# Generated by Django 3.2.13 on 2022-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_match_player_of_the_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umpire',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='umpire',
            name='last_name',
        ),
        migrations.AddField(
            model_name='umpire',
            name='name',
            field=models.CharField(default='alim dar', max_length=127),
            preserve_default=False,
        ),
    ]
