# Generated by Django 3.2.13 on 2022-05-15 18:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20220515_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umpire',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
    ]
