# Generated by Django 3.2.13 on 2022-05-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_umpire_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='match.team'),
        ),
    ]
