# Generated by Django 3.2.13 on 2022-05-16 05:55

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_match_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='test name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
    ]
